import React from 'react';
import { FiSliders, FiSmile, FiEyeOff, FiTrendingUp, FiCpu, FiFolder } from 'react-icons/fi';
import GlowCard from '../ui/GlowCard';

const FeaturesGrid = () => {
  const features = [
    {
      title: 'Algorithmic Radar Scan',
      description: 'Audit post captions and formatting structures against distribution ranking weights.',
      icon: FiSliders,
    },
    {
      title: 'Sentiment Evaluator',
      description: 'Expose positive, neutral, and negative semantic values which dictate feed recommendation pools.',
      icon: FiSmile,
    },
    {
      title: 'Shadowban Watchdog',
      description: 'Check posts against restricted hashtag lists and community guidelines before hitting publish.',
      icon: FiEyeOff,
    },
    {
      title: 'Reach Predictor',
      description: 'Calculate virality index and engagement potential using statistical distribution metrics.',
      icon: FiTrendingUp,
    },
    {
      title: 'AI Insight Explainer',
      description: 'Review structural guidelines generated by Gemini AI explaining precisely why metrics scored.',
      icon: FiCpu,
    },
    {
      title: 'Audit History Logs',
      description: 'Keep trace of all analyzed feeds, categorizing platforms to monitor your compliance history.',
      icon: FiFolder,
    }
  ];

  return (
    <section id="features" className="py-16 md:py-24 border-t border-slate-900 bg-slate-950/20">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center space-y-3 mb-16">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-indigo-400">
            Core Features
          </h2>
          <p className="text-2xl font-bold tracking-tight text-white sm:text-3xl">
            Exposing Distribution Engines
          </p>
          <p className="mx-auto max-w-lg text-xs text-slate-400">
            SocialXRay equips you with tools to audit compliance, predict visibility, and analyze feed filters.
          </p>
        </div>

        {/* Feature Grid */}
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <GlowCard key={feature.title} delay={index * 0.08}>
                <div className="space-y-4">
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-650/10 border border-indigo-500/10 text-indigo-400">
                    <Icon className="h-4.5 w-4.5" />
                  </div>
                  <h3 className="text-sm font-semibold text-slate-200">{feature.title}</h3>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </GlowCard>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default FeaturesGrid;
